version: "3.6"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "9091:9091/tcp"
    volumes:
      - "/home/stefan/wireguard:/config/wg_confs"
    restart: always

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    network_mode: "service:wireguard"
    depends_on:
      - wireguard
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "/home/stefan/transmission:/config"
      - "/media/Downloads/:/downloads"
    restart: always
