version: "3.6"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    group_add:
      - "105" # getent group render | cut -d: -f3
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    ports:
      - 8096:8096

volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
