version: "3.6"
services:
  transmission-openvpn:
    container_name: transmission-openvpn
    image: haugene/transmission-openvpn
    ports:
      - "9091:9091"
    restart: always
    cap_add:
      - NET_ADMIN
    secrets:
      - openvpn_credentials
    volumes:
      - "/home/stefan/openvpn/config:/config"
      - "/media/Downloads/:/data"
    environment:
      - OPENVPN_PROVIDER=PROTONVPN
      - OPENVPN_CONFIG=nl.protonvpn.net.udp,ch.protonvpn.net.udp
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_SPEED_LIMIT_UP=0
      - TRANSMISSION_SPEED_LIMIT_UP_ENABLED=true
      - TRANSMISSION_RATIO_LIMIT=0
      - TRANSMISSION_RATIO_LIMIT_ENABLED=true
      - TRANSMISSION_DOWNLOAD_QUEUE_ENABLED=false
    logging:
      driver: json-file
      options:
        max-size: 10m

secrets:
  openvpn_credentials:
    file: /home/stefan/openvpn/config/openvpn-credentials.txt
