version: "3.6"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    network_mode: host
    group_add:
      - "109" # getent group render | cut -d: -f3
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - /media:/media
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128

volumes:
  jellyfin-config:
    driver: local
  jellyfin-cache:
    driver: local
